; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
framework = stm32cube
board = nucleo_f767zi
build_type = debug
build_flags =
    -Icommon
monitor_speed = 115200
monitor_dtr = 1
monitor_filters = direct

[env:application]
board_build.ldscript = application.ld
build_src_filter =
    +<application/main.c>
    +<src/common>
build_flags =
    -DMCUBOOT_APPLICATION
    -DAPPLICATION_START=0x08020000

[env:bootloader]
; board_build.ldscript = bootloader.ld
build_src_filter =
    +<bootloader/main.c>
    +<src/common>
build_flags =
    -DMCUBOOT_BOOTLOADER
    -DMCUBOOT_PRIMARY_ONLY
    -DCONFIG_BOOT_SIGNATURE_TYPE_RSA
    -DCONFIG_BOOT_USE_MBED_TLS
    -Ilib/mcuboot/boot/bootutil/include
